# Data of Bank FD Customer

Predict if the customer will buy the FD or NOT ?

Target Column : 'y'

## Data Cleaning

In [ ]:
import pandas as pd
train = pd.read_csv("train.csv",sep=';')
test = pd.read_csv("test.csv",sep=';')

In [ ]:
train.head()

age           job  marital  education  ... pdays  previous poutcome   y
0   58    management  married   tertiary  ...    -1         0  unknown  no
1   44    technician   single  secondary  ...    -1         0  unknown  no
2   33  entrepreneur  married  secondary  ...    -1         0  unknown  no
3   47   blue-collar  married    unknown  ...    -1         0  unknown  no
4   33       unknown   single    unknown  ...    -1         0  unknown  no

[5 rows x 17 columns]

In [ ]:
train.shape,test.shape

((45211, 17), (4521, 17))

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        45211 non-null  int64 
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64 
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64 
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64 
 12  campaign   45211 non-null  int64 
 13  pdays      45211 non-null  int64 
 14  previous   45211 non-null  int64 
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB


In [ ]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        4521 non-null   int64 
 1   job        4521 non-null   object
 2   marital    4521 non-null   object
 3   education  4521 non-null   object
 4   default    4521 non-null   object
 5   balance    4521 non-null   int64 
 6   housing    4521 non-null   object
 7   loan       4521 non-null   object
 8   contact    4521 non-null   object
 9   day        4521 non-null   int64 
 10  month      4521 non-null   object
 11  duration   4521 non-null   int64 
 12  campaign   4521 non-null   int64 
 13  pdays      4521 non-null   int64 
 14  previous   4521 non-null   int64 
 15  poutcome   4521 non-null   object
 16  y          4521 non-null   object
dtypes: int64(7), object(10)
memory usage: 600.6+ KB


## NO NULL values !! 

- step 2: binarize the target column

In [ ]:
train['y'].unique()

array(['no', 'yes'], dtype=object)

In [ ]:
test['y'].unique()

array(['no', 'yes'], dtype=object)

- step 3 : convert string columns to numbers


- NOTE : here there are lot of columns for string to number conversion, so in that case a simple approach of one-hot encoding for all columns is used!

In [ ]:
train_new = pd.get_dummies(train,drop_first=True)

In [ ]:
test_new = pd.get_dummies(test,drop_first=True)

- Check number of columns after one hot encoding in training and test data both should be same

In [ ]:
train_new.shape, test_new.shape

((45211, 43), (4521, 43))

In [ ]:
train_new.columns

Index(['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'job_blue-collar', 'job_entrepreneur', 'job_housemaid',
       'job_management', 'job_retired', 'job_self-employed', 'job_services',
       'job_student', 'job_technician', 'job_unemployed', 'job_unknown',
       'marital_married', 'marital_single', 'education_secondary',
       'education_tertiary', 'education_unknown', 'default_yes', 'housing_yes',
       'loan_yes', 'contact_telephone', 'contact_unknown', 'month_aug',
       'month_dec', 'month_feb', 'month_jan', 'month_jul', 'month_jun',
       'month_mar', 'month_may', 'month_nov', 'month_oct', 'month_sep',
       'poutcome_other', 'poutcome_success', 'poutcome_unknown', 'y_yes'],
      dtype='object')

In [ ]:
test_new.columns

Index(['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'job_blue-collar', 'job_entrepreneur', 'job_housemaid',
       'job_management', 'job_retired', 'job_self-employed', 'job_services',
       'job_student', 'job_technician', 'job_unemployed', 'job_unknown',
       'marital_married', 'marital_single', 'education_secondary',
       'education_tertiary', 'education_unknown', 'default_yes', 'housing_yes',
       'loan_yes', 'contact_telephone', 'contact_unknown', 'month_aug',
       'month_dec', 'month_feb', 'month_jan', 'month_jul', 'month_jun',
       'month_mar', 'month_may', 'month_nov', 'month_oct', 'month_sep',
       'poutcome_other', 'poutcome_success', 'poutcome_unknown', 'y_yes'],
      dtype='object')

In [ ]:
train_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 43 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   age                  45211 non-null  int64
 1   balance              45211 non-null  int64
 2   day                  45211 non-null  int64
 3   duration             45211 non-null  int64
 4   campaign             45211 non-null  int64
 5   pdays                45211 non-null  int64
 6   previous             45211 non-null  int64
 7   job_blue-collar      45211 non-null  uint8
 8   job_entrepreneur     45211 non-null  uint8
 9   job_housemaid        45211 non-null  uint8
 10  job_management       45211 non-null  uint8
 11  job_retired          45211 non-null  uint8
 12  job_self-employed    45211 non-null  uint8
 13  job_services         45211 non-null  uint8
 14  job_student          45211 non-null  uint8
 15  job_technician       45211 non-null  uint8
 16  job_unemployed       4

- Drop repeated rows

In [ ]:
train_new.drop_duplicates(inplace=True)

In [ ]:
test_new.drop_duplicates(inplace=True)

In [ ]:
train_new.shape, test_new.shape

((45211, 43), (4521, 43))

- Drop columns where all values are same

In [ ]:
train_new.columns[train_new.nunique() == 1]

Index([], dtype='object')

- Drop the ID columns 

There is no ID column here

# Normalization

 STandard Scalar

- Split in X & Y

In [ ]:
X_train = train_new.drop("y_yes",axis=1)
Y_train = train_new["y_yes"]

In [ ]:
X_test = test_new.drop("y_yes",axis=1)
Y_test = test_new["y_yes"]

## Normalization of target column should not be done!!!

In [ ]:
from sklearn import preprocessing
x = X_train.values #returns a numpy array
std_scaler = preprocessing.StandardScaler()
std_scaler.fit(x)
x_scaled_std = std_scaler.transform(x)
X_train_std = pd.DataFrame(x_scaled_std,columns=X_train.columns)

In [ ]:
x = X_test.values
x_scaled_std = std_scaler.transform(x)
X_test_std = pd.DataFrame(x_scaled_std,columns=X_test.columns)

In [ ]:
X_train_std.describe()

age       balance  ...  poutcome_success  poutcome_unknown
count  4.521100e+04  4.521100e+04  ...      4.521100e+04      4.521100e+04
mean   5.222844e-16  3.070663e-15  ...     -1.030514e-13      5.035903e-14
std    1.000011e+00  1.000011e+00  ...      1.000011e+00      1.000011e+00
min   -2.159994e+00 -3.081149e+00  ...     -1.859480e-01     -2.116316e+00
25%   -7.473845e-01 -4.237719e-01  ...     -1.859480e-01      4.725192e-01
50%   -1.823406e-01 -3.002800e-01  ...     -1.859480e-01      4.725192e-01
75%    6.652252e-01  2.158743e-02  ...     -1.859480e-01      4.725192e-01
max    5.091402e+00  3.309478e+01  ...      5.377848e+00      4.725192e-01

[8 rows x 42 columns]

# Apply Classification algorithm

# Naive Bayes

there are 5 variants

- Gaussian NB :: for numeric columns

- Multinomial NB for multi nominal data / text data

- Complement NB improved multi nominal

- Bernoulli NB for binary columns

- Categorical NB for all columns which are categorical

In [ ]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB, \
                           ComplementNB, BernoulliNB, \
                           CategoricalNB

In [ ]:
clf_gnb = GaussianNB()
clf_gnb.fit(X_train_std, Y_train) # used for training
Y_pred_gnb = clf_gnb.predict(X_test_std)

In [ ]:
clf_bnb = BernoulliNB()
clf_bnb.fit(X_train_std, Y_train) # used for training
Y_pred_bnb = clf_bnb.predict(X_test_std)

In [ ]:
clf_mnb= MultinomialNB()
clf_mnb.fit(X_train_std, Y_train) # used for training
Y_pred_mnb = clf_mnb.predict(X_test_std)

ValueError: ignored

In [ ]:
clf_cnb = ComplementNB()
clf_cnb.fit(X_train_std, Y_train) # used for training
Y_pred_cnb = clf_cnb.predict(X_test_std)

ValueError: ignored

In [ ]:

clf_catnb = CategoricalNB()
clf_catnb.fit(X_train_std, Y_train) # used for training
Y_pred_catnb = clf_catnb.predict(X_test_std)

ValueError: ignored

# Support Vector Machine Classifier

In [ ]:
from sklearn.svm import SVC


In [ ]:
clf_svc = SVC()
clf_svc.fit(X_train_std, Y_train) # used for training
Y_pred_svc = clf_svc.predict(X_test_std)

# Decision Tree Classifier

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
clf_dt = DecisionTreeClassifier()
clf_dt.fit(X_train_std, Y_train) 
Y_pred_dt = clf_dt.predict(X_test_std)

# Random forest Classifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
clf_rf = RandomForestClassifier()
clf_rf.fit(X_train_std, Y_train) 
Y_pred_rf = clf_rf.predict(X_test_std)

# Compare the classifiers

In [ ]:
def evaluate_clf(Y_test, Y_pred):
  from sklearn.metrics import precision_recall_fscore_support
  p,r,f,s = precision_recall_fscore_support(Y_test,Y_pred)
  return p,r,f,s

In [ ]:
print("Gaussian NB")
print(evaluate_clf(Y_test, Y_pred_gnb))

Gaussian NB
(array([0.92534281, 0.38936535]), array([0.911     , 0.43570058]), array([0.91811539, 0.41123188]), array([4000,  521]))


In [ ]:
print("Burnoilli NB")
print(evaluate_clf(Y_test, Y_pred_bnb))

Burnoilli NB
(array([0.91741517, 0.37037037]), array([0.91925  , 0.3646833]), array([0.91833167, 0.36750484]), array([4000,  521]))


In [ ]:
print("SVM classifier")
print(evaluate_clf(Y_test, Y_pred_svc))

SVM classifier
(array([0.92744776, 0.80916031]), array([0.9875    , 0.40690979]), array([0.95653227, 0.54150702]), array([4000,  521]))


In [ ]:
print("DT classifier")
print(evaluate_clf(Y_test, Y_pred_dt))

DT classifier
(array([1., 1.]), array([1., 1.]), array([1., 1.]), array([4000,  521]))


In [ ]:
print("RF classifier")
print(evaluate_clf(Y_test, Y_pred_rf))

DT classifier
(array([1., 1.]), array([1., 1.]), array([1., 1.]), array([4000,  521]))


In [ ]:
import numpy as np
a = np.array([10,20,45,67])
np.random.seed(7)
#Seed must be between 0 and 2**32 - 1
np.random.randint(0,100,10)

array([47, 68, 25, 67, 83, 23, 92, 57, 14, 23])

In [ ]:
a #55,  7, 84,  7, 25, 11, 97, 89, 12, 49]

array([10, 20, 45, 67])